version: '3.0'
services:
  postgresLoginApp:
    image: postgres
    volumes:
      - ~/Projekty/volumesLoginApp/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
